### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by call-me-anything-you-want** [kinalmehta/marl-jax#3]
Hi, I'm trying to install the library following installation.md and ran into the following error:
> ERROR: Cannot install -r requirements.txt (line 43) and jax==0.4.1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested jax==0.4.1
>     chex 0.1.7 depends on jax>=0.4.6

any idea how to fix this?

**Comment by kinalmehta** [comment]
should be fixed in the latest commit

**Comment by call-me-anything-you-want** [comment]
problem solved, thanks
